#events
CASH_UPDATED_EVENT = "CASH_UPDATED_EVENT"
COINS_UPDATED_EVENT = "COINS_UPDATED_EVENT"
COIN_MODEL_UNLOCKED_EVENT = "COIN_MODEL_UNLOCKED_EVENT"
TOURNAMENT_UPDATED_EVENT = "TOURNAMENT_UPDATED_EVENT"
TOURNAMENT_STARTED_EVENT = "TOURNAMENT_STARTED_EVENT"